SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/home/aditya/Desktop/assignment-1-xor-verification-Adityapatil11/hdl/dut.v
VERILOG_SOURCES += $(PWD)/home/aditya/Desktop/assignment-1-xor-verification-Adityapatil11/wrapper/xor_test.v
TOPLEVEL = xor_test
MODULE = dut_test
include $(shell cocotb-config --makefiles)/Makefile.sim
